[package]
name = "harmonical"
version = "0.1.0"
edition = "2024"

[dependencies]
num2words = "1.2.0"
paste = "1.0.15"

[dev-dependencies]
approx = "0.5.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"